# SPDX-FileCopyrightText: Copyright (c) 2025 - 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bug Report
description: File a bug report for ALCHEMI Toolkit-Ops
title: "🐛[BUG]: "
labels: ["bug", "? - Needs Triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help ALCHEMI Toolkit-Ops and fill out this bug report!
        - By submitting this issue, you agree to follow our [Code of Conduct](./CONTRIBUTING.md)
        - You also confirm that you have searched the existing issues and have found no duplicates for this request

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of ALCHEMI Toolkit-Ops are you running?
      placeholder: "example: 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: On which installation method(s) does this occur?
      multiple: true
      options:
        - Docker
        - Pip
        - Source

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Please provide a complete and succinct description of the problem, including what you expected to happen.
      placeholder: XYZ occurred, I expected QRS results
    validations:
      required: true

  - type: textarea
    id: mvr
    attributes:
      label: Minimum reproducible example
      description: Please supply a [minimum reproducible code example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) here.
      render: python

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please paste relevant error and log output here
      render: shell

  - type: textarea
    id: env-details
    attributes:
      label: Environment details
      description: Please provide details about your environment
      placeholder: |
        + Environment location: [Bare-metal, Docker, Cloud (specify provider)]
        + GPU: [e.g., NVIDIA A100, H100]
        + CUDA version: [e.g., 12.4]
        + Python version: [e.g., 3.11]
        + PyTorch version: [e.g., 2.7.0]
        + NVIDIA Warp version: [e.g., 1.9.0]
        + If using Docker, provide `docker pull` & `docker run` commands used
      render: shell
